[gcloud]
disabled = true

[character] # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"

[sudo]
disabled = false

[nodejs]
format = "using [$symbol$version]($style) "
style = "bold green"
symbol = "ğŸ¢ "

[memory_usage]
format = "$symbol[${ram}]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false
symbol = "ğŸ’¿ "

[directory]
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "ğŸ£ "
style = "bold yellow"

